encoding: utf-8
locale: en-US
title: Alex's Blog
subtitle: Programming adventures
email: alex@oswaldtechnologies.com
description: >- # this means to ignore newlines until "baseurl:"
  My adventures in programming
url: "https://www.alexoswald.com"

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

minimal_mistakes_skin: "dark"
search: true
search_full_content: true

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      #classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

author:
  name: "Alex Oswald"
  avatar: "/assets/default-profile.png"
  bio: "Automation Engineer and .NET fanatic."
  location: "Bellevue, WA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oswaldtech"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oswaldtech"