title: Alex's Blog
email: alex@oswaldtechnologies.com
description: >- # this means to ignore newlines until "baseurl:"
  My adventures in programming
baseurl: ""
url: "http://alexoswald.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed