trigger:
  branches:
    include:
    - master
  tags:
    include: ['*']

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.5'
  inputs:
    versionSpec: '>= 2.5'

- script: 'gem install jekyll bundler'
  displayName: 'Install Jekyll and bundler'

- script: 'bundle install'
  displayName: 'Install Gems'

- script: 'bundle exe jekyll build'
  displayName: Build

- task: CopyFiles@2
  displayName: 'Copy "_site" to staging directory'
  inputs:
    SourceFolder: '_site'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: _site'
  inputs:
    ArtifactName: '_site'